package.json, src/Microcosm.js, src/Plugin.js, src/__tests__/Plugin-test.js, src/__tests__/install-test.js, src/install.js, src/tag.js
I want to eventually add some new things for plugins. This PR sets up the base object.
=> [add] Plugin class

package.json, src/Microcosm.js, src/Transaction.js, src/signal.js
Signal felt pretty gnarly, so I cleaned it up a bit my moving some of the logic out into a `Transaction` class. I also added "states" to Transactions to make it clearer what is going on.
=> Clean up transactions by making class

CHANGELOG.md, Makefile, package.json, src/send.js, src/tag.js, test/send-test.js, test/tag-test.js
=> Add warning when stores register actions to undefined handlers

docs/README.md, docs/api/connect.md, docs/api/provider.md
First pass. Hopefully this doesn't shamelessly copy Redux too much.
=> Add connection docs

README.md
=> Adds a pretty logo to the README

README.md
Adding a little more information to the main README, but keeping the link over to the more comprehensive docs.
=> Update documentation section of main README

CONTRIBUTING.md, README.md, circle.yml, package.json
and adds a shiny new coverage badge to the README
=> Restores Coveralls coverage reporting

docs/README.md, docs/recipes/testing-intents.md
I'm using a test helper for Presenter intents on my current project that I really like. I thought I'd make a recipe for it.
=> Add recipe for testing intents

src/action.js, src/microcosm.js
Suggested by @solomonhawk. Adds version numbers and explicit, consistent, deprecation statuses to existing deprecation warnings.
=> Improve deprecation messages

src/addons/presenter.js, test/addons/presenter.test.js
Name says it all!
Fixes https://github.com/vigetlabs/microcosm/issues/172
---
cc @greypants
=> Add warning in render method for Presenter

package.json, test/unit/action/constructor.test.js
=> Coverage fix

docs/api/domains.md, docs/api/effects.md, docs/api/microcosm.md
Also:
- Use new nested syntax for domain status registration
- Add similar entry for domain creation in microcosm.md
Related issues:
- https://github.com/vigetlabs/microcosm/issues/254
---
Documentation
No
=> Add documentation on creating effects and domains

src/action.js
This is a part of getting Microcosm ready to move over to Flow.
Related issues:
https://github.com/vigetlabs/microcosm/issues/305
=> Convert Action into an ES6 class

docs/api/presenter.md, src/addons/presenter.js
Adds examples for all presenter methods
---
=> Add documentation to presenter methods

README.md
I want to hit harder on what you get with Microcosm as early as possible.
Am I missing anything? Is this clear? 
It would also be cool to convert these points into tutorials, or explain them later in the readme. 
What do you think?
=> Add "What you get" section to the README

docs/api/history.md
- Documentation
Re: https://github.com/vigetlabs/microcosm/issues/334
=> Add documentation for History reconciliation and event emission

src/compare-tree/index.js, src/compare-tree/node.js, src/compare-tree/query.js, src/emitter.js, test/unit/compare-tree/compare-tree.test.js
This commit adds flow type coverage for CompareTree, Node, and Query
=> Add types for compare tree

src/install-devtools.js, src/microcosm.js, test/unit/microcosm/devtools.test.js
Adds the debug hook we need for the developer tools. This is related to:
https://github.com/vigetlabs/microcosm-devtools/pull/25
=> Add debug mode hook

docs/api/presenter.md
- Bugfix
- Feature
- Code style update
- Refactor
- Build tools
- Other, please describe:
- Yes
**Additional Information**
Includes more specific/accurate information about how/when `update` is called within Presenters. Specifically tries to disambiguate expectations similar to #372.
=> Improve specificity of Presenter `update` documentation

Makefile, package.json, rollup.config.js, src/microcosm.js
This is a work in progress PR for shipping Microcosm with ES6 module and UMD module bundles. It should fix #373 and work towards #362.
=> WIP: UMD and ES Bundles

docs/api/effects.md
- Documentation
- No
If yes, please describe the impact and migration path for existing applications:
**Additional Information**
=> Remove duplicate section on creating effects in docs

packages/microcosm-www-next/src/components/viget-logo.js, packages/microcosm-www-next/src/layouts/index.js, packages/microcosm-www-next/src/pages/index.js, packages/microcosm-www-next/src/stylesheets/app.scss, packages/microcosm-www-next/src/stylesheets/base/_elements.scss, packages/microcosm-www-next/src/stylesheets/setup/_colors.scss, packages/microcosm-www-next/src/stylesheets/setup/_dimensions.scss, packages/microcosm-www-next/src/stylesheets/structure/_footer.scss, packages/microcosm-www-next/src/stylesheets/structure/_main.scss, packages/microcosm-www-next/src/stylesheets/structure/_nav.scss, packages/microcosm-www-next/src/stylesheets/structure/_section.scss
- Finished styling all text
- Finished styling footer
- Started laying out elements in the main section; implemented spacing.
Below is how it looks like now:
=> styled text, footer; started laying out section

CONTRIBUTING.md
- Documentation
- No
(not applicable?)
=> Update CONTRIBUTING with the correct bootstrap command
