vigetlabs/microcosm

CHANGELOG.md
src/Store.js
src/__tests__/Store-test.js

cc @averyvery 
This PR makes all dispatched store actions be called within the scope of the store itself.

Fix store scope

---

.babelrc
CHANGELOG.md
package.json
src/Microcosm.js
src/Plugin.js
src/Store.js
src/__tests__/Microcosm-test.js
src/__tests__/Store-test.js
src/__tests__/run-test.js

This is mostly internal changes. However it highlights the beginning of trying to reduce the surface area of stores.
The biggest change here is how Stores accept actions:
```javascript
// Before
store.send(state, action, payload)
//After
Store.send(store, action, state, payload)
```
So now, this is a static method of `Store`. `send` is no longer on the prototype.
---
Summary of work:
1. Upgrade Foliage to 0.21.0
2. Move Store.prototype.send to Store.send. Change function signature to align more with other methods
3. Add `babel-plugin-object-assign` so that Object.assign can be used under the hood (transpiled polyfill)

Store refactor

---

package.json
src/Microcosm.js
src/Transaction.js
src/__tests__/Microcosm-test.js
src/__tests__/dispatch-generator-test.js
src/__tests__/dispatch-primitive-test.js
src/__tests__/dispatch-promise-test.js
src/chain.js
src/nodeify.js
src/signal.js

`app.push` now conducts the following behavior:
```javascript
// app.push(action, arguments, callback)
app.push(action, [ 'one', 'two', 'three' ], function(error, body) {
// error of failed iteration
// body of last iteration
})
```
I also picked up a few tricks from https://github.com/then/promise to ensure errors that occur in the callback do not get trapped by promise chains.
Also... I refactored `signal.js`, it feels quite a bit cleaner

v9.x callbacks

---

docs/guides/01-overview.md
src/Microcosm.js
src/Transaction.js
src/flatten.js

We do some work in places that we don't have to. This PR reduces the array allocation count of the transaction lifecycle tremendously. It also makes `clean` more granular, which will help with lifecycle methods later down the road.

Reduce some array allocations

---

package.json
src/install.js
src/plugin.js

This is a change from an outstanding branch that adds lifecycle methods. Not much, but plugins were instantiated on `start` before, which is problematic for the `appWillStart` lifecycle method :).

Refactor plugins for lifecycle methods

---

docs/api/plugins.md
examples/simple-svg/index.jsx
src/Microcosm.js
src/Store.js
src/Transaction.js
src/__tests__/Microcosm-test.js
src/__tests__/stores-test.js
src/attempt.js
src/chain.js
src/nodeify.js
src/plugin.js
src/remap.js
src/signal.js
src/tag.js

I'm starting to write the Microcosm dev tools and I noticed a couple of issues with our approach. Specifically, when I send transactions over `window.postMessage` to the Chrome extension, it includes a reference to the action type as a function. This is a problem when the browser attempts to serialize the object using this algorithm:
https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/The_structured_clone_algorithm
I still do not have an answer yet for `Error` objects returned by promises. They also don't serialize (which is really unfortunate). Still, this lays the groundwork.

Transaction refactor

---

package.json
src/Transaction.js
src/__tests__/transaction-test.js

Not too much to report here. I wanted the ability to set a payload when creating a transaction and I added the [flux-standard-action](https://github.com/acdlite/flux-standard-action) standard test into the suite.

Add ability to set payload on Transaction Create. FSA test

---

src/Microcosm.js

This commit renames and tweaks the update and error callbacks used by
Microcosm to process transactions to conform to more of a lifecycle
method of operation. This is a step towards actual lifecycle methods.

Add life cycle methods for transactions

---

CHANGELOG.md
package.json
src/Store.js
src/__tests__/stores-test.js

This commit allows the following behaviors:
```javascript
function Store() {
return {
[action]: (a,b) => a + b
}
}
```
```javascript
function Store() {
return {
[action]: 10
}
}
```
This is to support some future work on refactoring the store, dispatching process. It also opens up the flexibility for stores to interact with other parts.

Stores can have a diversity of registration methods.

---

src/Microcosm.js
src/__tests__/tag-test.js
src/dispatch.js
src/install.js
src/tag.js

I'm working on some future work that requires the `dispatch` method to be pure. This commit extracts the dispatch function into a separate module.

Make dispatch a pure function

---

src/__tests__/eventually-test.js
src/eventually.js

I want to support the following behavior:
```
app.push(action, params, reactComponent.method)
```
Up until now I was binding all `push` callbacks to `app`. That is problematic for this use case. Instead, I now use `call` inside of an anonymous function to respect `Function::bind`.
While I was at it, I also added test coverage to make sure that errors throw inside of `eventually` are not absorbed by promises. What a mind bender...

Respect bound callbacks. Add greater test coverage

---

src/__tests__/dispatch-generator-test.js
src/coroutine.js

This PR allows generators actions to compose other generator actions. Really, it fixes a bug where yielding generators returns the generator itself to the store. Keeping with the expectation, i want to continue to break down the complex data types until I get a primitive value.

Allow generators to use generators

---

src/__tests__/coroutine-test.js
src/coroutine.js

Allows for two way communication in generator actions:
```javascript
function* test () {
var first = yield Promise.resolve('test')
assert.equal(first, 'test')
var second = yield Promise.resolve(first.toUpperCase())
assert.equal(second, 'TEST')
}
```
So basically, you can lean on Microcosm to reduce the promise into a real value and perform future operations as if they were synchronous. Pretty cool.

Pass body into yield block.

---

benchmarks/dispatch-performance.js
src/Microcosm.js
src/Tree.js
test/Tree-test.js
test/dispatch-primitive-test.js
test/store-test.js

@solomonhawk and @mzlock found some fun issues in transaction history that would cause store handlers to execute more times than expected. We've addressed that in the latest beta release (9.14.1-beta), however I wanted to rethink this a bit.
There are a couple of changes:
- Do not re-evaluate state when a store is added. In future releases, I may consider throwing an error if a store is added after a Microcosm starts.
- `:start()` pushes the `willStart` lifecycle action instead of resetting. This sounds pretty obvious, I'm not sure why it wasn't this way before.
- Removed some `null` optimization checks that aren't necessary.

Nh revisit start and tree

---

examples/undo-tree/app/components/drawing.jsx
examples/undo-tree/app/undo-tree.js
src/Microcosm.js
src/Tree.js

This commit changes the order in which child nodes of the Tree data structure are appended. This allows for "redo" functionality that moves forward to the most recent change.

Tree should push children to beginning of list. Small Tree.js refactoring.

---

Makefile
benchmarks/push-performance.js

This PR adds another benchmark for general push performance. It's near instant, but I wanted to set up a benchmark before exploring some potential updates to this function.

Add push benchmark

---

docs/api/plugins.md
docs/guides/04-plugins.md
examples/simple-svg/app/plugins/render.js
src/install.js
test/plugin-test.js

If a plugin does not provide a `next` argument, it would be considered synchronous. This is to prevent the tedium of calling `next()` for otherwise synchronous tasks:
```javascript
const Logger  = {
register(app, options) {
app.listen(function() {
console.log("I changed!")
})
}
```

Plugins can be synchronous

---

src/Microcosm.js
src/Transaction.js
test/Microcosm-test.js
test/transaction-test.js

I hit this on a project and it got me thinking... Ideally the `Transaction` module shouldn't be presented to the developer. This is a private module. With that in mind, I moved the "bad action" error to `app.push`, and improved the messaging:

Move bad action pushing to app. Improve message

---

src/install.js
test/Microcosm-test.js

If `app.start()` is invoked and no callback is provided, errors passed through the plugin process will raise an exception. 
Basically, I'm tired of having to do this by hand on every single project:
```javascript
app.start(function(error) {
if (error) {
throw error
}
})
```

Start throws errors by default if not provided a callback

---

src/update.js
test/mutation-test.js
test/update-test.js

Microcosm maintains a pair of methods for writing to `app.state`: `get` and `set`. This PR makes a change to `set` so that it first checks to see if a value has actually changed before overwriting it.

Do not clone objects when the target value is the same

---

src/Transaction.js
src/eventually.js
src/update.js
test/dispatch-generator-test.js
test/dispatch-promise-test.js
test/eventually-test.js
test/mutation-test.js
test/update-test.js

Since the addition of the [unpromise](https://github.com/vigetlabs/microcosm/blob/master/src/unpromise.js) function, Promise try/catch behavior no longer affects Microcosm internals. This means that we do not need to execute the callback of `app.push` within a set timeout.
This PR makes that change, and makes some updates to a few timeout-related tests that cut the test suite by a couple hundred milliseconds.
Technically, this also probably means that app.push callbacks execute quite a bit faster, but the real value here is that there's simply less machinery.

Eliminate the need to set a timeout on every callback

---

src/Microcosm.js
src/install.js
test/Microcosm-test.js

Adds a helpful error to let you know you probably forgot to call `app.start()` if trying to push before doing so.

Throw error if push() called before start()

---

src/Tree.js

Small thing, but I added a depth property to each node in `Tree.js`, which makes determining the size of the tree operate at constant time. With this efficiency, the Tree `reduce` function can lean on `size()` to be quite a bit faster as well.
These benchmarks are approximate, and don't account for variance, but:
```
Nodes  ::append()  ::root()  ::reduce(merge)  ::size()  ::prune()  Memory Growth
-----  ----------  --------  ---------------  --------  ---------  -------------
10000  0.0007ms    0.0240ms  2.84ms           0.55ms    1.13ms     0.476%
```
```
Nodes  ::append()  ::root()  ::reduce(merge)  ::size()  ::prune()  Memory Growth
-----  ----------  --------  ---------------  --------  ---------  -------------
10000  0.0007ms    0.0210ms  1.81ms           0.03ms    0.85ms     0.447% …
```

Add depth calculation to nodes to make size() constant.

---

benchmarks/dispatch-performance.js
benchmarks/tree-performance.js
src/Tree.js
test/Tree-test.js

Another fun one. Instead of storing the children of a history tree node as an array, I store it as a linked list on the existing node object. This prevents an array allocation. In order to calculate children, I've set up a getter that returns an arrayified version of this linked list.
The result is drastically reduced tree operations, and a much lighter memory footprint overall. Also, this improves performance so much that I increased the test benchmarks from 10,000 to 50,000 nodes.
```
Nodes  ::append()  ::root()  ::reduce(merge)  ::size()  ::prune()  Memory Growth
-----  ----------  --------  ---------------  --------  ---------  -------------
50000  0.0011ms    0.0250ms  11.77ms          0.03ms    3.98ms     0.812%
18.61ms to dispatch 50000 actions (50 samples)
- 162.70mbs of memory
- …
```

Reduce memory footprint even lower

---

src/addons/connect/index.js
test/addons/connect-test.jsx

This is an experimental option for the Connect addon that enables it to
call `valueOf` on the value returned from a computed property. This
should open up a number of possibilities for writing query DSLs.
Basically, I want to support the following:
```javascript
var ViewModel = Connect(function (props) {
return {
users: Users.where({ job: 'Programmer' }).limit(10)
}
})
```
In this example, we can provide perf optimizations to the query under the hood without exposing it to the user.

Add valueOf option to Connect

---

.eslintrc.json
README.md
package.json
src/getStoreHandlers.js
test/tree.test.js

- Fixes a bug where eslint was run against no files.
- Adds linting of JS code in markdown documents.
- Fixes an unused var issue in a test.
- Ignores another unused var issue in a different test. (I can't find a
great way to ignore unused vars assigned to `_`.)

Update linting process

---

docs/README.md
docs/recipes/ajax.md

Easy enough. cc @ltk 
I haven't covered cancellation or progress. These are special cases that I want to give their own recipes. Thoughts?

Add AJAX recipe to documentation

---

docs/api/microcosm.md
examples/react-router/app/todos.js
src/microcosm.js

Tapping into `super` within the constructor when extending Microcosm feels too low level. What do you think about adding a setup step? Personally, I think it indicates the intent much clearer.
Replaces:
```javascript
class SolarSystem extends Microcosm {
constructor(options) {
super(options)
this.addStore('planets', Planets)
}
}
```
With:
```javascript
class SolarSystem extends Microcosm {
setup() {
this.addStore('planets', Planets)
}
}
```
This also eliminates a friction point: remembering to pass `options` into `super()`.

Add setup method

---

src/microcosm.js
src/tree.js

Some tree methods create anonymous functions to get around scope
issues. Since we control the entire system, we can just pass scope
in as a third argument. This cuts down on some memory usage and makes
these methods a tad faster.

Add scope argument to tree methods

---

src/getStoreHandlers.js
test/helpers/console.js
test/store.test.js

Before this commit, there was an error in the way stores report missing
handlers. They would check for `undefined` within the `register()`
function, however actions now have extra states that are referenced as
properties. We can no longer make this check when dispatching.
One alternative would be to use a Proxy. In the meantime, this commit
removes the warning and reduces another error to a warning.
Fixes #133

Do not aggressively throw on missing actions

---

docs/api/stores.md
docs/recipes/immutable-js.md
package.json
src/getStoreHandlers.js
src/microcosm.js
src/store.js
test/custom-store.test.js
test/dispatch.test.js
test/immutable-interop.test.js
test/microcosm.test.js
test/mutation.test.js
test/store.test.js

I want to better support custom APIs for Stores and the use of complex data libraries such as ImmutableJS. To do that, stores need to be more powerful:
```javascript
class ImmutableStore extends Store {
getInitialState() {
return Immutable.Map()
}
shouldCommit(next, previous) {
return Immutable.is(next, previous) === false
}
add(state, record) {
return state.set(record.id, record)
}
remove(state, id) {
return state.remove(id)
}
commit(state) {
return Array.from(state.values())
}
register() {
return {
[create]  : this.add,
[destroy] : this.remove
}
}
}
```
**What's new**:
This PR adds several new options to stores:
```
setup - A one time preparation method called right after a store is added
set - How should a store assign a value?
commit - How should a store expose a value publicly?
``` …

Make stores more powerful

---

docs/api/presenter.md
src/addons/presenter.js
test/addons/presenter.test.js
test/helpers/console.js

Sometimes a presenter just wants to subscribe to all state changes. We can't just return `this.repo.state`, because the view model is only recalculated when a presenter receives new props.
So here's my solution: support returning a function that is given the current repo state:
```javascript
class MyPresenter extends Presenter {
viewModel() {
return state => state
}
render() {
return <p>Test</p>
}
}
```
Or, to quickly extract several keys:
```javascript
class MyPresenter extends Presenter {
viewModel() {
return ({ dogs, cats }) => ({ dogs, cats })
}
render() {
return <p>Test</p>
}
}
```
We'll also now warn if `this.repo.state` is returned from the view model. What do you think?

Warn when returning repo.state, allow viewmodel function

---

src/addons/presenter.js
src/addons/provider.js
test/addons/presenter.test.js
test/addons/provider.test.js

Instead of throwing an error by default, Presenters just pass along children (if they can). This sort of makes the `Provider` addon pointless. Should we kill it?

Consolidate provider

---

docs/README.md
docs/api/with-intent.md
src/addons/with-intent.js
test/addons/presenter.test.js
test/addons/withIntent.test.js

We have a Form add-on that connects to Presenters. @cwmanning has been utilizing a `withIntent` higher-order component that is better suited for buttons, or other components:
```javascript
const DestroyButton = withIntent(function ({ send }) {
return (
<button onClick={() => send('destroy-thing')}>
Nuke this thing
</button>
)
})
class Users extends Presenter {
register() {
return {
'destroy-thing': repo => repo.push(destroyThing)
}
}
render() {
// Kind of silly, probably better to use a callback prop here, but imagine
// this is deep in the component tree
return <DestroyButton />
}
}
```
Should we be more restrictive with passing down send? Something like `withIntent("intent-name", Component)`. We could add extra validations to make sure the intents are connected properly, and it might …

withIntent addon

---

CHANGELOG.md
docs/api/presenter.md
src/addons/presenter.js
test/addons/presenter.test.js

Adds `teardown(repo, props)`. This is useful for reversing anything done in `setup()`
cc @cwmanning

Teardown, opposite of Setup

---

CHANGELOG.md
docs/README.md
docs/api/microcosm.md
docs/recipes/testing-domains.md
src/microcosm.js
test/action.test.js

I just hit this on a project and thought it would be cool to provide a canonical answer for testing domain handlers:
```javascript
const repo = new Microcosm()
const identity = n => n
repo.addDomain('test', {
register () {
return {
[identity.open] : () => 'open',
[identity.done] : () => 'done'
}
}
})
repo.append(identity).open()
assert.equal(repo.state.test, 'open')
repo.append(identity).close()
assert.equal(repo.state.test, 'done')
```
1. Adds back `append()`. I removed it before, but this was a mistake. Let's officially support it.
2. Adds a testing recipe for domain handlers

Setup easier testing for domain handlers

---

src/domains/meta.js
src/getDomainHandlers.js
src/lifecycle.js
src/microcosm.js
test/register.test.js

Basically don't let this happen:
```javascript
const repo = new Microcosm()
repo.addDomain('test', {
test() {
console.log("bad bad bad!")
}
})
repo.push('test')
```
This is important because I want to support broadcasting actions as intents within `withIntent` and presenters.

Do not support string key access on domain dispatch

---

src/action.js
src/history.js
test/action.test.js

Before this commit it was possible to cancel a resolved action, reject a
cancelled action, etc... This commit makes it impossible to change the
state of an action after it has been marked for clean up.
Also:
- When history archives an action to strip all event listeners.
- Reorganize action tests into suites for individual states.

Disposed actions should not change

---

docs/api/microcosm.md
src/action.js
src/history.js
src/microcosm.js
test/action.test.js
test/microcosm.test.js

When the second argument of `Microcosm::patch` or `Microcosm::reset` is
true, Microcosm will call `deserialize on the provided data payload.
```javascript
repo.reset({ users: [{ id: 'bob' ] }, true) // will deserialize
repo.patch({ users: [{ id: 'bob' ] }, true) // will deserialize
```
Fix #158

Add deserialize option to patch and reset

---

src/addons/presenter.js
test/addons/presenter.test.js

https://twitter.com/dan_abramov/status/790581793397305345:
> Don’t subscribe to data sources in constructor or componentWillMount(). Use componentDidMount(), teardown in componentWillUnmount().
So we don't, anymore. I've also removed `this.pure` in favor of `this.isImpure()`.

Subscribe to repo on mount

---

src/emitter.js
test/emitter.test.js

Before this commit, one time event subscription followed a different
pattern than regular event subscription. This lead to extra conditions
in code. This commit reworks subscriptions to allow a third argument:
the number of times the subscription should emit.
By default, this is Infinity.

Rework one-time event subscription

---

CHANGELOG.md
package.json
src/addons/presenter.js
test/addons/presenter.test.js

This allows the method to be accessed from the `Presenter` directly.
Basically so we can do pass the `send` method from a presenter to other classes or functions in the setup method: 
```js
class MySocketyPresenter extends Presenter {
setup(repo) {
this.sockets = {
chat: new IntentSocket(`graph/${id}/chat`, this.send), 
graph: new IntentSocket(`graph/${id}/graph`, this.send)
}
}
}
```

Make send directly available to Presenter

---

CHANGELOG.md
docs/api/presenter.md
src/addons/presenter.js
test/addons/presenter.test.js

```
class MyPresenter extends Presenter {
view = MyView
}
```

View can be a react component

---

CHANGELOG.md
docs/api/form.md
package.json
src/addons/form.js
test/addons/form.test.js

Just bumped into this on our hackathon project. This PR makes it much easier to format data before submitting it:
```javascript
class SchedulesNew extends React.Component {
transform (params) {
params.start = new Date(params.start).toISOString()
params.end = new Date(params.start).toISOString()
return params
}
render () {
return (
<Form intent={actions.create} onError={this.onFailure} transform={this.transform}>
<p><label>Name <input name="name" /></label></p>
<p><label>Start <input name="start" type="datetime-local" /></label></p>
<p><label>End <input name="end" type="datetime-local" /></label></p>
<footer>
<input type="submit" />
</footer>
</Form>
)
}
}
export default SchedulesNew
```

Form transform

---

CHANGELOG.md
src/domains/meta.js
src/microcosm.js
test/fork.test.js

Forks inherit state. If a parent repo's state contains a key, it will
pass the associated value down to a child. This allows state to flow
downward through the repo network.
Unfortunately, this causes an unexpected behavior with `patch` where
consecutive actions always operate on the original patched value, and
not the new state produced by a child.

Patching on child repos should not effect parents

---

src/addons/with-intent.js
src/display-name.js
test/addons/withIntent.test.js
test/display-name.test.js
test/helpers/logger.js

I just hit an issue where calling `withIntent` returns a stateless (function) component and the Presenter thought it was a plain old `view()` method. That meant that `withIntent` never received proper context 😢.
**withIntent displays a few nice warnings now:**
**Presenters always call `React.createElement` on their view**.
This means that the new signature for a view method is:
```javascript
view (model, context) {
return <Component />
}
```
Generally, I would like to move away from using `view` as a method and always assign it as an inline property or getter. Having a `view` method that returns JSX has been a source of confusion when I solicit feedback about the abstraction.
---
1. Should we raise an exception instead of gracefully failing? 
2. Is the Presenter tweak (calling …

Warn when withIntent is called as function

---

docs/api/presenter.md
src/addons/presenter.js
test/addons/presenter.test.js

This commit adds an extendable getRepo method to the Presenter
prototype that allows custom repo assignment behavior. For example, if
we wanted to avoid the default forking behavior:
```javascript
class NoFork extends Presenter {
getRepo (repo) {
return repo
}
}
```

Allow custom repo behavior in Presenter

---

CHANGELOG.md
src/action.js
test/action.test.js

Action payloads may now intentionally be set to undefined. We'll also make them undefined by default.
---
Should fix #198

Payload definition

---

bench/history-performance.js
src/action.js
src/emitter.js
src/history.js
src/microcosm.js
test/history.test.js
test/microcosm.test.js
test/middleware/promise-middleware.test.js

This PR started out as a way to fix some edge cases when disabling actions. However along the way I discovered some pretty nice performance improvements.
It changes the way the History module traverses the action tree. Instead of building an array, it uses a linked list. Additionally, I removed some babel compilation for argument parameters in Action to avoid building an array when calling `resolve`, `error`, etc. 
- Action memory usage is roughly 1/5 of master
- Appending actions is roughly 5x faster (strange how that worked out)
- Pushing actions is roughly 2x faster
So pretty neat! Also the build size is a little smaller too.

Improve performance and memory usage of history

---

CHANGELOG.md
docs/api/presenter.md
src/addons/presenter.js
src/addons/with-intent.js
test/addons/presenter.test.js
test/addons/withIntent.test.js

We found ourselves wrapping the direct children of the Presenter component with `withIntent` quite often. This PR configures the Presenter to pass down `send` along with the model.
Fixes #203

Pass Presenter send method along with model

---

CHANGELOG.md
src/addons/presenter.js
test/addons/presenter.test.js

The repo prop from a presenter was getting sent into the view. This
commit overrides that prop with new fork.
Fixes #208
cc @greypants

Send fork of repo into view

---

CHANGELOG.md
package.json
src/microcosm.js
test/serialization.test.js

This commit fixes an issue where calling deserialize and serialize on
a fork lost access to serialization processes on parents:
```
const parent = new Microcosm()
const child = parent.fork()
parent.addDomain('fiz', {
getInitialState: () => 'fiz',
serialize: word => word.toUpperCase()
})
child.addDomain('buzz', {
getInitialState: () => 'buzz',
serialize: word => word.toUpperCase()
})
expect(child.serialize()).toEqual({ fiz: 'FIZ', buzz: 'BUZZ' })
```
In this case, the parent is the owner of `fiz`. It should be responsible for initial serialization.
cc @mackermedia

Serialization should include parents

---

package.json
src/addons/presenter.js
src/microcosm.js
src/utils.js
test/computed-props.test.js
yarn.lock

This commit adds a new feature for memoizing complex state
computations.
- `query` allows you to extract a fragment of state using key paths, like `"users,ui.region"`
- `index` allows you to assign a query to a string name
- `compute` allows you to calculate an index, optionally passing functions for additional processing
I'd like to keep this a private API until we can really nail things down, but here's an example usage for one of the projects I'm testing it on:
```javascript
class StrategiesHistoricalPresenter extends Presenter {
view = Historical
setup (repo) {
repo.index('series', 'strategies,ui.focused,ui.region', byRegion('strategies'))
}
model ({ location }, _, repo) {
const { query } = location
return {
query      : query,
region     : state => state.ui.region,
series     : …
```

Add API for memoization

---

src/addons/jest-matchers.js
src/lifecycle.js
test/action.test.js
test/dispatch.test.js
test/domain.test.js
test/effects.test.js
test/microcosm.test.js
test/mutation.test.js
test/register.test.js
test/rollbacks.test.js
test/serialization.test.js

Reset and patch return an action. This PR sets those actions up so that they are rejected whenever deserializing their payloads fail.
Deserialize still raises an exception. 
I've also added a new test helper for quickly testing repo state in a safe way.

Reset and patch reject when deserialize fails. Add new test helper

---

docs/api/presenter.md
docs/guides/quickstart.md
src/addons/presenter.js
test/addons/presenter.test.js

Whew! I finally wrapped this up! This implements the new updates to Presenters:
```javascript
class SolarSystem extends Presenter {
setup () {
// runs before `this.getModel` has executed. Useful for setting up a repo fork
}
ready () {
// runs after setup, and the first model calculation
console.log(this.model) // [{ id: "mercury" }, { id : "venus" } ...]
}
getModel () {
return {
planets: state => state.planets
}
}
render () {
const { planets } = this.model
return <PlanetsView planets={planets} />
}
}
```
- Presenters that do not implement a model do not listen to repo changes.
- `view` always calls React.createElement
- `render` works as an other React component
- Presenters have access to the current calculated model via `this.model`
- The `update` hook has access to the latest model
- …

Presenter updates

---

docs/api/data-utilities.md
src/realm.js
src/utils.js
test/utils.test.js

Updates utility methods to avoid recursion, offering a small perf boost. Also allows keys to be set as dot notation paths like:
```javascript
set(obj, 'a.b.c', value)
```
It also adds an `update` helper. Often times, we want to modify data in place. This commit adds an `update` helper that works like a combination of `get` and `set`:
```javascript
import { update } from 'microcosm'
let votes = { yay: 0, nay: 0 }
let next = update(votes, 'yay', n => n + 1)
console.log(next) // { yay: 1, nay: 0 }
```
`update` also excepts a fallback value. If the provided target is missing, the keypath is missing, the processor function will be called with the fallback value:
```javascript
import { update } from 'microcosm'
let votes = { yay: 0, nay: 0 }
let next = update(votes, 'undecided', n => n + 1, 0) …
```

General utility improvements, add update utility helper

---

bench/history-performance.js
src/action.js
src/addons/jest-matchers.js
src/archive.js
src/history.js
src/microcosm.js
src/realm.js
src/utils.js
test/addons/presenter.test.js
test/unit/history/archive.test.js
test/unit/history/checkout.test.js
test/unit/history/toArray.test.js
test/unit/microcosm/dispatch.test.js
test/unit/reconciliation.test.js
test/unit/utils/backfill.test.js

I'm working on an undo/redo feature on a project and I already bumped into issues where we over-eagerly rollback actions. So I fixed it. This commit changes the action resolution algorithm so that history only needs to roll back to the point of change, preventing excessive Domain handler modification.
For example, assuming the following tree:
```
1-done -> 2-open -> 3-open -> 4-open -> 5-open -> 6-done
```
**Before:**
1. action 5 finishes: Process 2,3,4,5,6
2. action 4 finishes: Process 2,3,4,5,6
3. action 3 finishes: Process 2,3,4,5,6
4. action 2 finishes: Process 2,3,4,5,6
5. Mark 6 as the next root
**After:**
1. action 5 finishes: Process 5,6
2. action 4 finishes: Process 4,5,6
3. action 3 finishes: Process 3,4,5,6
4. action 2 finishes: Process 2,3,4,5,6
5. Mark 6 as the next root
This …

History improvements

---

src/history.js
test/unit/history/invoke.test.js

This commit fixes a bug where Microcosm would raise an exception if a
fork was removed from history as the result of a parent changing. It
also adds an assertion to make it clearer during testing.
Sorry, @dce :(

Invoke should not run on removed repos

---

CHANGELOG.md
package.json
src/history.js
src/microcosm.js
test/unit/microcosm/release.test.js

This commit prevents a bug where children would not receive the latest
updates when their parents emitted a change event.
I believe this was introduced in 12.1.0.

Properly release state changes to children

---

CHANGELOG.md
package.json
src/addons/presenter.js
src/lifecycle.js
src/microcosm.js
test/addons/presenter.test.js
test/unit/microcosm/addDomain.test.js
test/unit/microcosm/lifecycle.test.js
test/unit/microcosm/patch.test.js

Available for testing by installing `microcosm@12.2.1-alpha.0`
- adding domains does not reset state
- patching parents with keys owned by children does not patch children
- patch does not reset state in forks
- new children props re-render presenters
- presenter.send method is autobound, allowing it work when passed to children
---
Related issues:
https://github.com/vigetlabs/microcosm/issues/260
https://github.com/vigetlabs/microcosm/issues/259

Fix patch domains

---

CHANGELOG.md
docs/README.md
docs/api/history.md
package.json
site/src/layouts/default.html
src/history.js
test/unit/history/then.test.js
test/unit/history/wait.test.js

On one of our current projects, we have a bit of a hack to wait for all actions to complete before running a test. I want to more formally support that, and add some documentation around how it works. 
This commit adds promise interop for action history. This is useful for waiting for history to complete before doing some other type of work. It also adds documentation for history, which is somewhat unstable still, something we clarify in the doc.
With this PR, you can now do:
```javascript
describe('An AJAX behavior', function() {
it('adds a user', async function () {
let repo = new MyMicrocosm({ maxHistory: Infinity })
repo.push(getUser, 1)
repo.push(getUser, 2)
repo.push(getUser, 3)
await repo.history
expect(repo.users.length).toEqual(3)
})
})
```
I need way more infographics for this. …

Add history.wait() feature to wait for all outstanding actions

---

CHANGELOG.md
docs/api/microcosm.md
src/microcosm.js
test/unit/microcosm/constructor.test.js
test/unit/microcosm/setup.test.js

We frequently pass custom options into Microcosm to configure Domains and Effects with different options based on the environment. For example, an Effect that auto-saves user data:
```javascript
class Repo extends Microcosm {
setup ({ saveInterval }) {
// ...
this.addEffect(Autosave, { saveInterval })
}
}
```
It can be cumbersome to chase down the default options, which may be specified as defaults in individual domains/effects. With this release, you may now define defaults using the `defaults` static:
```javascript
class Repo extends Microcosm {
static defaults = {
saveInterval: 5000
}
setup ({ saveInterval }) {
// ...
this.addEffect(Autosave, { saveInterval })
}
}
```
Before this change, setting default options had to occur with the default arguments feature of ES6:
```javascript
class …
```

Add a way to configure default options. Add default options

---

CHANGELOG.md
Makefile
docs/guides/installation.md
rollup.config.js
site/src/layouts/default.html

This commit adds strict mode: a special bundle of Microcosm that
includes development-only assertions. It also adds an installation
guide for setting up strict mode with Webpack.
Fixes:
https://github.com/vigetlabs/microcosm/issues/280

Add strict mode

---

CHANGELOG.md
docs/api/actions.md
src/addons/jest-matchers.js
src/coroutine.js
test/unit/middleware/generator-middleware.test.js

Often times we need to dispatch multiple actions in sequential order. For example, what if we want to ask the user to confirm their action before deleting a record?
This can be accomplished by using a generator:
```javascript
function ask (message) {
return action => {
if (confirm(message)) {
action.resolve()
} else {
action.reject()
}
}
}
function deleteUser (id) {
return fetch.delete('/users/${id}').then(response => response.json())
}
function confirmAndDelete (user) {
return function * (send) {
yield send(ask, `Are you sure you want to delete ${user.name}?`)
yield send(deleteUser, user.id)
}
}
```
Each `yield` in the generator processes sequentially. A parent action is returned from `repo.push()` to represent the entire sequence. If any action is cancelled or rejected along the way, …

Generators define sequences of actions

---

docs/api/actions.md
src/coroutine.js
test/unit/middleware/generator-middleware.test.js

cc @efatsi 
It doesn't make sense to obscure the repo during an action generator sequence. Let's just pass it straight in:
```javascript
function sleep (time) {
return action => {
setTimeout(() => action.resolve(true), time)
}
}
function dream (time) {
return function * (repo) {
yield repo.push(sleep, time)
yield repo.push(sleep, time)
yield repo.push(sleep, time)
}
}
repo.push(dream, 100)
```

Rework generator sequence

---

CHANGELOG.md
docs/api/microcosm.md
package.json
src/addons/presenter.js
src/microcosm.js
test/addons/presenter.test.js
test/unit/domain/teardown.test.js
test/unit/effect/teardown.test.js
test/unit/history/invoke.test.js
test/unit/microcosm/events.test.js
test/unit/microcosm/shutdown.test.js

Domains, Effects, and Presenters have a teardown method that runs when a Microcosm shuts down. Oddly, Microcosms didn't have this behavior themselves. This commit adds a dedicated teardown hook to Microcosm, and a private `shutdown` method to trigger it.
```javascript
class Repo extends Microcosm {
setup () {
// runs when a Microcosm starts
}
teardown () {
// runs when a Microcosm ends
}
}
```
I kind of wonder if there's something here with live reloading. Like with a dedicated `setup` and `teardown`, you could, in theory, completely reboot a Microcosm instance.
With a getInitialState/setup/teardown, Microcosm's now implement the exact same interface as Domains. I wonder if we could do something with this
I'm still not quite sure how to expose `shutdown`. What do you think? Should we keep …

Add teardown callback to Microcosm

---

CHANGELOG.md
docs/api/actions.md
docs/recipes/ajax.md
src/coroutine.js
src/microcosm.js
test/unit/microcosm/push.test.js
test/unit/middleware/promise-middleware.test.js

Name says it all
```javascript
function getPlanet (id) {
return fetch(`/planets/${id}`).then(res => res.json())
}
let action = repo.push(getPlanet, 'mars')
action.onOpen(data => console.log(data))
// 'mars'
action.onDone(data => console.log(data))
// { id: 'mars', name: 'Mars' }
```
Related issues:
https://github.com/vigetlabs/microcosm/issues/296

Pass first argument of action parameters as open state of promises

---

.babelrc
CHANGELOG.md
Makefile
docs/api/actions.md
package.json
rollup.config.js
src/action.js
test/unit/action/autobinding.test.js
test/unit/action/cancelled.test.js
test/unit/action/complete.test.js
test/unit/action/done.test.js
test/unit/action/error.test.js
test/unit/action/open.test.js
test/unit/action/update.test.js
yarn.lock

Action status methods, like `action.resolve()`, or `action.reject()` are now auto-bound. This means that you can pass them directly into a callback, and the scope of the method will remain as the action. 
This is particularly useful when working with AJAX libraries. For example, when working with `superagent`:
```javascript
import superagent from 'superagent'
function getPlanets () {
return action => {
let request = superagent.get('/planets')
request.on('request', action.open)
request.on('progress', action.update)
request.then(action.resolve, action.reject)
}
}
```
I struggled with adding this for a long time. Auto-binding generally increases memory usage and adds extra instantiation overhead. However, using a getters to lazy-generate the functions seems to do the trick. 
I also added a …

Action status methods are autobound

---

src/key-path.js
test/unit/key-path/get-key-paths.test.js

Pretty cut and dry. I'm working on some stuff that uses key paths and I noticed that spaces aren't allowed. This PR allows for change subscriptions like:
```javascript
repo.on('lists, items', callback)
// or
repo.on('lists,items', callback)
```
Not a new feature, it's just natural to add a space after a comma, so let's make sure we cover it.

Handle spaces in key paths, increase key path test coverage

---

src/addons/presenter.js
test/addons/presenter.test.js

This PR does two things: 
1. Model callbacks are invoked within the scope of the presenter
2. The current repo is passed as the second argument
Context otherwise gets lost when you pass a reference to a Presenter method in getModel:
```javascript
class MyPresenter extends Presenter {
getModel(props) {
return {
key: this.process
}
}
process () {
// You'd expect `this` to be the presenter, right?
}
}
```
This lets you do neat things, like push actions if data is missing
```javascript
function getUsers (state, repo) {
let users = get(state, 'users', [])
if (users.length <= 0) {
repo.push(getUsers)
}
return users
}
class UsersPresenter extends Presenter {
getModel(props) {
return {
users: getUsers
}
}
}
```
There's some more nuance to that sort of thing to prevent over-fetching, but the basic …

Presenter model callbacks maintain scope, pass repo

---

docs/api/actions.md
docs/api/microcosm.md
src/action.js
src/coroutine.js
src/microcosm.js
test/unit/middleware/generator-middleware.test.js

This commit adds the ability to batch together a group of actions under a parent "group" action. If all of the actions complete or cancel, the group resolves. Otherwise the action is categorically rejected.
This surfaces itself through a new Microcosm method: `repo.all([...actions])`: 
```javascript
let group = repo.all([
repo.push(actionOne),
repo.push(actionTwo)
])
group.onDone(function () {
console.log('hurrah!')
})
```
Additionally, generator actions can yield an array:
```javascript
function fetchUsers(usersList) {
return function*(repo) {
let requests = usersList.map(repo.prepare(fetchUser))
yield requests
}
}
```
**What kind of change does this PR introduce?** 
**Related issues:**
- …

Adds repo.all for parallel actions. Sugar in yield action format.

---

CHANGELOG.md
src/action.js
test/unit/action/complete.test.js
test/unit/action/done.test.js
test/unit/action/error.test.js
test/unit/action/open.test.js
test/unit/action/update.test.js

This allows for use cases like, "Cancel this action, but only if it hasn't finished yet.":
```javascript
class PlanetsList extends Presenter {
getModel () {
return {
planets: state => state.planets
}
}
setup (repo) {
this.action = repo.push(getPlanets)
}
teardown () {
// We no longer care about this
this.action.cancel()
}
// ...
}
```
---

Do not warn in strict mode when changing a completed action

---

src/history.js
test/unit/history/isActive.test.js
test/unit/history/remove.test.js

If yes, please describe the impact and migration path for existing applications:
**Additional Information**
This PR fixes two bugs:
- If you remove an action which has no `next` reference, History assumed you were removing the head action and automatically set the head to the action's parent. This ensures that the head is reset only if the action being removed was the existing head.
- If you remove the head action, set the head to the removed action's parent

Fix bugs in history.remove

---

src/action.js
src/history.js
test/unit/history/__snapshots__/toJSON.test.js.snap
test/unit/history/toJSON.test.js

This allows serialization of history for developer tools. This lets you do:
```javascript
JSON.stringify(repo.history) 
// { size: 3, root: { id: 0, status: 'resolved', payload: true, children: [...] }
```
This is for:
https://github.com/vigetlabs/microcosm-devtools

Implement toJSON for Action and History

---

src/domain-engine.js
src/microcosm.js
test/addons/presenter.test.js
test/unit/microcosm/patch.test.js
test/unit/microcosm/register.test.js

Microcosms can now declare a custom register and getInitialState method. In this way, they behave exactly like domains.
This does not allow Microcosms to be added as domains to other Microcosms. That will require some work. This is intended to make it easier to introduce Microcosm, and for concise examples.
```javascript
const ADD = 'ADD'
class Repo extends Microcosm {
getInitialState() {
return { count: 0 }
}
add(state, n) {
return update(state, 'count', value => value + n)
}
register() {
return {
[ADD]: this.add
}
}
}
let repo = new Repo()
repo.push(ADD, 2)
repo.push(ADD, 2)
expect(repo).toHaveState('count', 4)
```
---
**Does this PR fulfill these …

Microcosms can be register to actions

---

src/compare-tree/index.js
src/compare-tree/query.js
src/key-path.js
test/unit/compare-tree/query.test.js
test/unit/key-path/get-key-paths.test.js

Microcosm has an internal tree for comparing data. This is so that you can do things like `repo.on('change:planets', (planets) => {})`. This commit reduces some responsbilities inside of the comparison tree itself so that individual nodes have greater encapsulation.
I've also added an efficiency for calculating keypaths that avoids re-parsing array-form keypaths. Paths that are already in the correct form are not additionally parsed. 
For example:
```javascript
let path = [['foo', 'bar']]
let parsed = castPath(path)
assert.equal(path, parsed)
```

Move more query/node concerns to their associated modules

---

.eslintrc.json
.flowconfig
flow/registry.js
package.json
src/domain-engine.js
src/effect-engine.js
src/key-path.js
src/registration.js
yarn.lock

Adds flow types for the domain and effect engines. Still lots of Flow learning to do. 
One thing I'm curious about are data types. For example, checkout `Registration`. I'm using a class for this, but is that appropriate? Generally I don't like to use classes for "data bags", but having the type automatically generated is nice.
Also I'm finding places where my code is simply too general (see `utils.js :: createOrClone`). I could see some eventual refactoring here to make things more explicit.

Add flow types for domain and effect engines

---

flow/registry.js
src/domain-engine.js
src/utils.js
test/unit/utils/clone.test.js
test/unit/utils/merge.test.js

This commit adds flow types to the utilities module. It also uncovers an optimization where we can avoid returning a new object when the right-most value of a `merge` call is a superset. For example:
```javascript
let left = { green: true }
let right = { green: true, blue: true }
let answer = merge(left, right)
expect(answer).toBe(right)
```
We can just return the right-most value because it contains no differences with the left.

Add flow types to utilities. Optimize merge.

---

src/history.js

Now that we can group actions, [history.wait()](http://code.viget.com/microcosm/api/history.html#wait) can be simplified.

Simplify history.wait()

---

src/addons/presenter.js
test/addons/presenter.test.js

Presenter `intercept` hooks were getting invoked in the wrong context.
Fixes #363

Presenter context bug

---

src/domain-engine.js
src/lifecycle.js
src/meta-domain.js
src/microcosm.js
src/utils.js

This commit reworks the sanitization process to avoid some extra inefficiency. Additionally it cuts some code from the domain engine.
This was bugging me for a while since @efatsi pointed it out. Hopefully this makes things a bit nicer.

Rework sanitize process, simplify domain engine

---

src/addons/presenter.js

This PR fixes an issue where the React hot loader could cause infinite recursion.
Kudos to @solomonhawk 
---
- Bugfix
- No

Avoid infinite recursion with hot reloading

---

src/action.js
src/archive.js
src/history.js
src/symbols.js
src/utils.js
test/unit/history/archive.test.js
test/unit/history/iterator.test.js
test/unit/history/map.test.js
test/unit/history/remove.test.js
test/unit/history/updater.test.js

This commit implements the iterator interface for history. This is important for interoperability with other libraries: specifically Observables.
```
// Enumerate over history
for (var action of repo.history) {
console.log(action)
}
// Or quickly build an array from history
let activeBranch = Array.from(repo.history)
// Or wait for all history to finish
Observable.of(repo.history).subscribe({ next, error, complete })
```

History is an iterator

---

flow/snapshot.js
src/domain-engine.js
src/history.js
src/microcosm.js
src/utils.js
test/integration/efficiency.test.js
test/integration/nested-actions.test.js
test/integration/reexecuting-domain-handlers.test.js
test/integration/rollbacks.test.js
test/integration/snapshots-in-forks.test.js
test/unit/microcosm/addDomain.test.js

This commit changes the way we store snapshots such that they have context into their last operation. This lets us memoize domain handlers. Basically:
1. Is the prior snapshot value the same?
2. Is the prior action status the same?
3. Is the prior action payload the same?
If so, don't invoke the domain handler again!
Testing this in the wild, this has cut extra domain handler invocation for lots of async tasks by about 30%. Pretty neat.
I also believe that we could use this new approach for reporting in the developer tools. We _could_ eventually store each of these snapshots as a diff.
Additionally, if we were to support sub-domains #184, this caching would become more and more powerful as your key paths became more specific. Breaking up complicated state management would get faster.

Cache domain handlers when possible

---

CHANGELOG.md
docs/api/domains.md
docs/api/effects.md
flow/domain.js
src/domain-engine.js
src/effect-engine.js
src/microcosm.js
src/utils.js
test/unit/domain/construction.test.js
test/unit/domain/setup.test.js
test/unit/effect/construction.test.js
test/unit/effect/setup.test.js

Domains and effects can have a `defaults` class property to provide default setup options:
```javascript
class Counter {
static defaults = {
start: 0
}
setup (repo, { start }) {
console.log(start) // 0
}
}
let repo = new Microcosm()
repo.addDomain('counter', Counter) // default start is 0
```
---
Fixes #384.

Allow a cascade of options. Add static defaults to domains and effects

---

CHANGELOG.md
src/domain-engine.js
src/utils.js
test/unit/compare-tree/compare-tree.test.js
test/unit/utils/get.test.js

Just got hit by this nasty bug. Getting `null` out of an object was returning undefined because the loose null check returned an undefined fallback:
```
get({ prop: null }, 'prop') // undefined, but should be null
```
This is because we trigger the fallback on null. The problem is that a value is present here, so we should respect it when there is no fallback.

Do not return undefined when getting null with no fallback

---

.github/ISSUE_TEMPLATE.md

Adds a test reproduction link to the github issue template:
https://jsfiddle.net/w2m0mang/
Also I found, when writing issues, that I spent a lot of time removing template boilerplate. I've consolidated the sections a bit. This is totally up for discussion. cc @leobauza

Add test case link, update github template

---

flow/domain.js
src/get-registration.js
src/microcosm.js

Makes returning an object optional. Cuts an object allocation on every new action push because we don't need to return an object in the default Microcosm register method.

Make register object optional

---

CHANGELOG.md
docs/api/domains.md
src/domain-engine.js
test/unit/domain/construction.test.js

This PR adds the mount point to the options passed to domains. It can be accessed from `options.key` in `setup` and the constructor.
```javascript
let repo = new Microcosm()
class Planets {
setup(repo, options) {
console.log(options.key) // "planets"
}
}
repo.addDomain('planets', Planets)
```
Fixes https://github.com/vigetlabs/microcosm/issues/396.

Pass the domain key to construction options

---

CHANGELOG.md
docs/api/actions.md
docs/api/domains.md
docs/api/effects.md
src/coroutine.js
test/unit/middleware/thunk-middleware.test.js

See #367 
**Question**: Should we do this? Does this make anything harder to do? Theoretically this could be a breaking change if someone is returning an argument and expecting it to be executed as a thunk (passing a thunk action body as an argument from the `repo.push` callsite) which seems like a potentially legitimate use case.
- Code style update
- Refactor
- Build tools
- Documentation
- Other, please describe:
- No
If yes, please describe the impact and migration path for existing applications:
If you were passing a function as an action parameter when calling `repo.push` or `send` and then returning it as the value from within the action body _and_ expecting that function-argument to be …

#367 Coroutine can distinguish between thunks and pass-through params

---

packages/microcosm/CHANGELOG.md
packages/microcosm/src/action.js
packages/microcosm/src/history.js
packages/microcosm/src/microcosm.js
packages/microcosm/test/addons/indexes.test.js
packages/microcosm/test/unit/microcosm/constructor.test.js
packages/microcosm/test/unit/microcosm/setup.test.js

This commit removes support for the ability to reset state when a Microcosm is created. 
```javascript
let repo = new Repo({}, {
planets: [ 'earth', 'mars', 'jupiter']
})
```
You mostly see this in tests, and it looks goofy. It's also easy to miss the third argument, which tells Microcosm to deserialize the data (like take string JSON and turn it into an object). Beyond that, there are a couple of other reasons:
1. I only want one way to reset state
2. It can be confusing to look at constructors that include seed data, particularly when deserialized
3. This is part of an effort to reduce some extraneous use cases to improve learnability/useabillity
4. You can't listen to failure (`repo.reset().onError(...)`)
I also took at pass at improving some tests around instantiation options while I …

Remove ability to reset Microcosm on construction

---

packages/microcosm/src/history.js
packages/microcosm/src/microcosm.js

**What**
Microcosm determines application state by taking a list of actions (history) and using their results to calculate a new state. When an action changed, History would emit a change event for that action and every action that followed it in this list.
This is a lot of events! Instead, this commit changes the strategy so that it only emits the _range_ of actions; the start and the end.
**Why**
Two reasons:
1. I want to eventually replace event emitters with [observables](https://github.com/tc39/proposal-observable), which more accurately match how actions work. This gets rid of one of those events "update" event, meaning we only need to figure out how to handle "remove", then we can drop the event emitter abstraction.
2. Performance. Because a Microcosm is responsible for iterating …

History changeset

---

packages/microcosm/src/history.js
packages/microcosm/src/microcosm.js
packages/microcosm/test/unit/history/append.test.js

**What:**
Microcosm History emits an `append` event that tells its associated Microcosms that it needs to create a snapshot. We can lazily generate snapshots as they are needed, allowing us to get rid of that event.
**Why:**
I am trying to move internals over to [observables](https://github.com/tc39/proposal-observable), which more accurately describe how Microcosms and Actions work. To do that, I need to eliminate a few events, particularly in History.
Basically I'm trying to get everything to work via a single `change` event type, which could eventually be replaced with the observable lifecycle:
1. start (setup microcosm hook)
2. next (change microcosm hook)
3. complete (teardown microcosm hook)
4. error (handled via actions)

Generate snapshots as needed. Remove append event subscription

---

packages/microcosm/src/addons/action-form.js
packages/microcosm/test/addons/action-button.test.js
packages/microcosm/test/addons/action-form.test.js

This commit ensures that both the ActionForm and ActionButton are
referenceable via refs, and can be submitted programmatically.
Fixes #446

ActionForm and ActionButton are referenceable via refs

---

packages/microcosm/docs/api/microcosm.md
packages/microcosm/src/action.js
packages/microcosm/test/unit/action/link.test.js

We encountered an issue on an app using 12.12.x where we needed the
payloads from `repo.parallel` when it completed. This commit upstreams
that change.
Partially fixes https://github.com/vigetlabs/microcosm/issues/428

Upstream repo.parallel fix

---

packages/microcosm/docs/api/actions.md
packages/microcosm/src/action.js
packages/microcosm/src/coroutine.js
packages/microcosm/src/utils.js
packages/microcosm/test/unit/action/link.test.js
packages/microcosm/test/unit/middleware/generator-middleware.test.js

This commit updates repo.parallel such that it can accept plain JavaScript objects. In this case, the return payload is an object who's keys match the shape provided.
This also allows generator actions to yield objects
```javascript
function getPost (id) {
return fetch(`/posts/${id}`)
}
function getComments (id) {
return fetch(`/posts/${id}/comments`)
}
function getPostWithComments (id) {
return function * (repo) {
let { post, comments } = yield { post: repo.push(getPost, id), comments: repo.push(getComments, id) }
post.comments = comments
return post
}
}
repo.push(getBlogPost, 1)
```

Repo.parallel can accept objects

---

packages/micromanage/README.md
packages/micromanage/package.json

This PR starts micromanage, what I consider to be the missing piece of Microcosm: a data management and querying layer. Domains work reasonably well enough as data-bags, however I'm not happy with how low level their data management operations are. Consider:
```javascript
import { Domain } from 'microcosm'
function getWidget (id) {
return fetch(`/widgets/${id}`).then(res => res.json)
}
class Widgets extends Domain {
getInitialState() {
return []
}  
addWidget(widgets, widget) {
return widgets.concat(widget)
}
register() {
return {
[getWidget]: this.addWidget
}
}  
}
class WidgetShow extends Presenter {
getModel(repo, { id }) {
return {
widget: repo.domains.widgets.map(widgets => widgets.find(w => w.id === id))
}
}
ready(repo, props) {
repo.push(getWidget, props.id)
}
update(repo, props) { …
```

Micromanage inception

---

jest.config.js
packages/micromanage/jest.config.js
packages/micromanage/src/entity.js
packages/micromanage/src/index.js
packages/micromanage/src/strings.js
packages/micromanage/test/entity.test.js

This commit adds an initial draft of schemas. If an entity is created without a schema, it fails. Additionally, if a property does not match the schema, it fails. Essentially:
```javascript
class Planet extends Entity {
static schema = {
name: String
}
}
let earth = new Planet({ name: 'earth' })
let invalid = new Planet({ name: 2 })
// Raises exception:
// 'Entity "Planet" expected a String for key "name". Instead found Number.'
```
**Is this too strict?**
I like the strictness, but I also know that it would be a bummer for an API to change a string or number field, or decide to return null. I still need to figure out the best approach for that.
One idea is to allow it, with an option to send warnings about schema mismatches in a backchannel. You'd get an alert about the issue, but a user …

[micromanage] Add schemas

---

jest.config.js
packages/microcosm/src/agent.js
packages/microcosm/src/domain.js
packages/microcosm/src/effect.js
packages/microcosm/src/history.js
packages/microcosm/src/index.js
packages/microcosm/src/ledger.js
packages/microcosm/src/microcosm.js
packages/microcosm/src/proto.js
packages/microcosm/src/registry.js
packages/microcosm/src/subject.js
packages/microcosm/test/helpers.js
packages/microcosm/test/unit/history/__snapshots__/toJSON.test.js.snap
packages/microcosm/test/unit/history/iterator.test.js
packages/microcosm/test/unit/history/toJSON.test.js
packages/microcosm/test/unit/history/toggle.test.js
packages/microcosm/test/unit/microcosm/addDomain.test.js
packages/microcosm/test/unit/microcosm/addEffect.test.js
packages/microcosm/test/unit/microcosm/patch.test.js
packages/microcosm/test/unit/subject.test.js

This commit adds a new class to describe the dispatch behavior: an agent. Agents receive action dispatches from history and can manage their own internal state:
```javascript
import { start, stop } from '../actions/gps'
class GPS extends Agent () {
setup() {
this.listen()
}
listen() {
this.watcher = navigator.geolocation.watchPosition(this.next)
}
ignore() {
navigator.geolocation.clearWatch(this.watcher);
}
receive(action) {
switch(action) {
case start: 
return this.listen()
case stop: 
return this.ignore()
default: 
return null
}
}
}
let gps = new GPS()
gps.subscribe(next => console.log(next)) // location.... location .... location....
gps.send(start)
```
I still haven't figured out the public API for Agents yet, but I think they will be a useful escape hatch for creating new types of …

[microcosm] Unify effect and domain behavior through agent class

---

LICENSE
README.md

@g-clef pointed out that we're missing a root-level license. This was an oversight when we moved to a mono-repo approach to manage all of the packages under the microcosm umbrella.
This commit addresses that, fixing #501.

Add license to repo root and reference in readme

---

packages/microcosm/src/domain.js
packages/microcosm/src/observable.js
packages/microcosm/test/unit/domain/register.test.js
packages/microcosm/test/unit/subject-map.test.js
packages/microcosm/test/unit/subject.test.js

This PR updates Observable such that the first "next" callback invokes immediately. This is important for Observable::map, particularly when binding data in React. Otherwise, React renders before the scheduler clears the queue for an observable. So you'll end up with something like:
```javascript
class UserShow extends Presenter {
getModel(repo, { id }) {
let { users } = repo.domains
return {
user: users.map(users => find(users, { id })
}
}
render() {
console.log(this.model.user) 
// Always undefined initially because the observable callback is still
// in the scheduler
}
}
```
Essentially, this makes it so that you can always get a value immediately, even if the initial payload is empty.

[microcosm] Always, synchronously, emit the first observer.next()

---

packages/microcosm/src/history.js
packages/microcosm/src/microcosm.js
packages/microcosm/test/unit/history/archive.test.js

**What**
This commit adds back the max history option to Microcosm, a feature of 12.x that controls how many actions Microcosm's history should hold on to.
This is based upon depth, not overall action count. This is so that you can checkout prior trees. For example:
```
action-0__________
/        \         \
action-1  action-2  action-3__________
/        \         \
action-4  action-5  action-6__________
/        \         \
action-7  action-8  action-9___________
/        \          \
action-10 action-11  action-12___________
/         \          \
action-13  action-14  action-15
/         \
action-16  action-17
```
This is with a size of 10, though in this case, the overall depth hasn't hit higher than 6. With a size of 3, this would look like:
```
action-0__________
/        \ …
```

Add back max history option

---

packages/microcosm/src/observable.js
packages/microcosm/src/scheduler.js
packages/microcosm/test/setup.js
packages/microcosm/test/unit/observable.test.js

**What**
Adds [flow type](https://flow.org/en/) definitions for Microcosm's scheduler.
**Why**
The scheduler is a critical piece of Microcosm 13, and it didn't have any flow type coverage.
Adding flow types uncovered a bug where Observable was accessing the scheduler's error handler from the wrong namespace. This PR additionally adds test coverage for that case.

[microcosm] Add flow types for scheduler

---

flow/snapshot.js
src/domain-engine.js
src/microcosm.js
test/integration/rollbacks.test.js

This commit fixes a bug where toggling an action would not invalidate snapshot cache state, resulting in an incorrect state:
```javascript
repo.addDomain('test', {
getInitialState() {
return true
}
})
let action = repo.reset({ test: false })
action.toggle()
expect(repo).toHaveState('test', true)
action.toggle()
expect(repo).toHaveState('test', false) // This failed
```
The solution is to track disabled action state as a part of the snapshot, just like the status and payload field.
Resolves:
https://github.com/vigetlabs/microcosm/issues/525

Always reapply a snapshot after toggling
